services:
  - type: web
    name: display-stock-api
    runtime: docker
    plan: free
    region: virginia
    healthCheckPath: /health
    envVars:
      - key: Auth__Username
        sync: false
      - key: Auth__PasswordHash
        sync: false
      - key: Database__Initialize
        value: "true"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        sync: false
